var TOP = [{
    "title": "Slub Jersey Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2PV%200229888%20002%2081%200513.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=0&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Tops",
    "color": "Pink",
    "price": "$17.95",
    "description": "Striped top in soft slub jersey. Chest pockets, short sleeves with sewn cuffs and roll-up tab and button, and raw-edge neckline.",
    "detail": "33% polyester, 67% cotton.",
    "history": 0,
    "hsv": {h: 21, s: 10, v: 92},
}, {
    "title": "V-neck Jersey Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200215248%20009%2034%205134.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Tops",
    "color": "Turquoise",
    "price": "$5.95",
    "description": "Fitted top in soft stretch jersey with a V-neck and short sleeves.",
    "detail": "95% cotton, 5% spandex.",
    "history": 0,
    "hsv": {h: 176, s: 72, v: 66},
}, {
    "title": "Draped Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200224369%20001%2017%205608.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Tops",
    "color": "Black melange",
    "price": "$29.95",
    "description": "Long, sleeveless top in slub jersey with seam along center of back. Raw-edge, rounded hem with a longer, slightly draped back section.",
    "detail": "15% linen, 85% rayon.",
    "history": 0,
    "hsv": {h: 270, s: 11, v: 15},
}, {
    "title": "Lyocell-blend Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200214447%20003%2095%206042.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=4&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Tops",
    "color": "White",
    "price": "$39.95",
    "description": "CONSCIOUS. Straight-cut top in a fine-knit wool and lyocell blend. Slightly longer back section with half in woven, recycled polyester. Slits at sides and short sleeves with sewn cuffs.",
    "detail": "50% lyocell, 50% wool.",
    "history": 0,
    "hsv": {h: 51, s: 6, v: 94},
}, {
    "title": "Lace-trimmed Blouse",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200225914%20002%2047%205898.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=4&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Tops",
    "color": "Light pink",
    "price": "$17.95",
    "description": "Blouse in airy woven fabric with short ruffled sleeves. Lace inserts at front, opening at back, and hook-and-eye fastener at back of neck.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 18, s: 11, v: 96},
}, {
    "title": "Wide-cut Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2OV%200219359%20008%2097%205736.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Tops",
    "color": "Gray",
    "price": "$12.95",
    "description": "Wide-cut top in jersey with short dolman sleeves. Diagonal slits at sides and seam at center back.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 260, s: 6, v: 60},
}, {
    "title": "Jersey Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2QV%200194823%20010%2016%209385.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Tops",
    "color": "Blue",
    "price": "$9.95",
    "description": "CONSCIOUS. Short-sleeved, fitted top in organic cotton jersey with printed design at front. Rolled raw edges at neckline and cuffs.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 221, s: 33, v: 72},
}, {
    "title": "Jersey Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200218113%20012%2015%205564.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=0&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Tops",
    "color": "Black",
    "price": "$12.95",
    "description": "T-shirt in jersey with printed design.",
    "detail": "40% polyester, 60% cotton.",
    "history": 0,
    "hsv": {h: 283, s: 20, v: 14},
}, {
    "title": "Oversized Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AV%200194302%20001%2016%207840.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Tops",
    "color": "White",
    "price": "$14.95",
    "description": "Oversized jersey top with printed design at front. Short sleeves and slightly wider neckline.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 60, s: 0, v: 93},
}, {
    "title": "Polo Shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2MV%200135471%20027%2035%205114.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Tops",
    "color": "Dark blue/dotted",
    "price": "$12.95",
    "description": "CONSCIOUS. Fitted polo shirt in organic cotton stretch fabric.",
    "detail": "97% cotton, 3% spandex.",
    "history": 0,
    "hsv": {h: 226, s: 31, v: 28},
}, {
    "title": "V-neck Jersey Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200177768%20010%2077%204703.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Tops",
    "color": "Khaki green",
    "price": "$12.95",
    "description": "Short-sleeved top in slightly sheer slub jersey with raw edges at cuffs and hem.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 43, s: 35, v: 47},
}, {
    "title": "V-neck Jersey Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200215248%20009%2034%205134.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Tops",
    "color": "Turquoise",
    "price": "$5.95",
    "description": "Fitted top in soft stretch jersey with a V-neck and short sleeves.",
    "detail": "95% cotton, 5% spandex.",
    "history": 0,
    "hsv": {h: 176, s: 72, v: 66},
}, ];
var SHIRTS_BLOUSES = [{
    "title": "Wrap-front Blouse",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200225690%20005%2096%200034.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=4&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shirts & Blouses",
    "color": "Light blue",
    "price": "$29.95",
    "description": "Blouse in woven fabric with a wrapover front section. Long sleeves with roll-up tab and button.",
    "detail": "100% rayon.",
    "history": 0,
    "hsv": {h: 224, s: 27, v: 86},
}, {
    "title": "Stretch Shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AV%200105800%20085%2035%207578.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Office wear",
    "color": "Pink/Striped",
    "price": "$19.95",
    "description": "Fitted, long-sleeved shirt in stretch fabric with V-neck. Buttons at front and at cuffs.",
    "detail": "30% cotton, 28% nylon, 2% spandex, 40% polyester.",
    "history": 0,
    "hsv": {h: 343, s: 7, v: 95},
}, {
    "title": "Stretch Shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/V28%200105800%20001%2096%202164.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=5&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Office wear",
    "color": "Black",
    "price": "$19.95",
    "description": "Fitted, long-sleeved shirt in stretch fabric with V-neck. Buttons at front and at cuffs.",
    "detail": "4% spandex, 30% nylon, 66% cotton.",
    "history": 0,
    "hsv": {h: 288, s: 14, v: 14},
}, {
    "title": "Peasant Blouse",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2KV%200209994%20001%2077%204724.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shirts & Blouses",
    "color": "White",
    "price": "$34.95",
    "description": "CONSCIOUS. Blouse in an airy, woven organic cotton fabric. Buttons and embroidery at top, inset lace trim, and 3/4-length sleeves with elasticized cuffs. Smocking at hem.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 46, s: 7, v: 92},
}, {
    "title": "Crinkled Lace Blouse",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200219571%20002%2055%203121.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shirts & Blouses",
    "color": "Dark blue",
    "price": "$24.95",
    "description": "Straight-cut blouse in airy, crinkled chiffon with lace yoke. Long sleeves, pearlescent buttons at back of neck and at cuffs, and lightweight jersey lining.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 229, s: 31, v: 28},
}, {
    "title": "Oversized Shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200212601%20001%2068%200462.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shirts & Blouses",
    "color": "White",
    "price": "$34.95",
    "description": "Wide, straight-cut shirt in woven fabric with long sleeves. Side slits and one chest pocket. Slightly longer at back.",
    "detail": "30% polyester, 70% rayon.",
    "history": 0,
    "hsv": {h: 40, s: 5, v: 93},
}, {
    "title": "Cotton Shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2KV%200206903%20004%2067%204727.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shirts & Blouses",
    "color": "Taupe",
    "price": "$24.95",
    "description": "Straight-cut shirt in soft cotton fabric with two chest pockets and short button placket. Rounded hem. Slightly longer at back.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 31, s: 13, v: 62},
}, {
    "title": "V-neck Blouse",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200209336%20004%2015%205565.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Office wear",
    "color": "Dark blue",
    "price": "$29.95",
    "description": "V-neck blouse in airy woven fabric. 3/4-length sleeves with roll-up tab and button, inverted pleat at front, and rounded hem. Slightly longer at back.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 234, s: 28, v: 29},
}, {
    "title": "Peasant Blouse",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2IV%200214658%20001%2081%209723.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shirts & Blouses",
    "color": "White",
    "price": "$29.95",
    "description": "Blouse in airy crinkled cotton with embroidery and 3/4-length sleeves. Ties at top, elasticized trim with decorative ruffles at neckline and cuffs. Rounded hem, slightly longer at back.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 38, s: 3, v: 91},
}, {
    "title": "V-neck Blouse",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AI%200199079%20004%2094%208776.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shirts & Blouses",
    "color": "Powder beige",
    "price": "$24.95",
    "description": "V-neck blouse in airy woven fabric. Buttons at front, long sleeves with roll-up tab and button, chest pockets, and rounded hem with slits at sides. Slightly longer at back.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 26, s: 16, v: 88},
}, ];
var CARDIGANS_SWEATERS = [{
    "title": "Loose-knit Sweater",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2JV%200215983%20007%2031%208633.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Cardigans & Sweaters",
    "color": "Cerise",
    "price": "$19.95",
    "description": "Loose-knit, V-neck sweater in ribbon yarn with 3/4-length sleeves. Small slits at sides. Slightly longer at back.",
    "detail": "35% nylon, 65% acrylic.",
    "history": 0,
    "hsv": {h: 345, s: 69, v: 89},
}, {
    "title": "Sweatshirt with Text",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2GV%200218858%20002%2096%203358.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Cardigans & Sweaters",
    "color": "Mint green",
    "price": "$10",
    "description": "Long-sleeved sweatshirt with text at front. Ribbed cuffs and hem. Brushed inside.",
    "detail": "50% cotton, 50% polyester.",
    "history": 0,
    "hsv": {h: 174, s: 22, v: 88},
}, {
    "title": "Cropped Sweatshirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200221979%20005%2067%200290.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Cardigans & Sweaters",
    "color": "Light pink",
    "price": "$10",
    "description": "Cropped sweatshirt with ribbed cuffs and hem.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 13, s: 26, v: 97},
}, {
    "title": "Sweatshirt with Text",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2MV%200218858%20004%2018%203607.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Cardigans & Sweaters",
    "color": "Gray",
    "price": "$10",
    "description": "Long-sleeved sweatshirt with text at front. Ribbed cuffs and hem. Brushed inside.",
    "detail": "50% polyester, 50% cotton.",
    "history": 0,
    "hsv": {h: 48, s: 3, v: 76},
}, {
    "title": "Fine-knit Sweater",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2GV%200192872%20004%2066%208504.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Cardigans & Sweaters",
    "color": "White/Striped",
    "price": "$9.95",
    "description": "Sweater in a loose, fine knit with long sleeves. Short slits at sides. Slightly longer at back.",
    "detail": "55% polyester, 45% rayon.",
    "history": 0,
    "hsv": {h: 40, s: 4, v: 86},
}, {
    "title": "Quilted Sweatshirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2PV%200234237%20001%2017%205850.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Cardigans & Sweaters",
    "color": "Gray",
    "price": "$34.95",
    "description": "Long-sleeved sweatshirt in quilted fabric with ribbed cuffs and hem.",
    "detail": "2% spandex, 17% cotton, 81% polyester.",
    "history": 0,
    "hsv": {h: 40, s: 3, v: 75},
}, {
    "title": "Fine-knit Cardigan",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AE%200149075%20033%2016%201536.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Cardigans & Sweaters",
    "color": "Mustard yellow",
    "price": "$10",
    "description": "Fine-knit cardigan with a round neckline, long sleeves, and front buttons.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 36, s: 74, v: 93},
}, {
    "title": "Fine-knit Sweater",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2BV%200160530%20025%2016%201532.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Cardigans & Sweaters",
    "color": "Blue",
    "price": "$19.95",
    "description": "Long, loose-fitting, fine-knit sweater with long sleeves.",
    "detail": "40% cotton, 60% rayon.",
    "history": 0,
    "hsv": {h: 224, s: 66, v: 52},
}, {
    "title": "Fine-knit Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2IV%200203625%20004%2016%208550.jpg]&set=key[rotate],value[15.35]&set=key[width],value[600]&set=key[height],value[702]&set=key[x],value[2085]&set=key[y],value[919]&set=key[type],value[DETAIL]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Cardigans & Sweaters",
    "color": "Mint green",
    "price": "$14.95",
    "description": "Loose, fine-knit top with ribbed texture and slightly wider-cut style. 3/4-length sleeves with sewn cuffs.",
    "detail": "1% spandex, 99% rayon.",
    "history": 0,
    "hsv": {h: 170, s: 16, v: 91},
}, {
    "title": "Rib-knit Sweater",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2IA%200218185%20001%2096%200310.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Cardigans & Sweaters",
    "color": "White",
    "price": "$24.95",
    "description": "Short, rib-knit sweater in a soft cotton blend.",
    "detail": "60% cotton, 40% acrylic.",
    "history": 0,
    "hsv": {h: 54, s: 4, v: 94},
}, ];
var DRESSES = [{
    "title": "Lace Dress",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200167978%20019%2087%200194.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=4&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Dresses",
    "color": "Black",
    "price": "$17.95",
    "description": "Knee-length, sleeveless jersey dress with lace yoke. Gently flared skirt with narrow, removable tie belt at waist. Lace trim at hem.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 255, s: 17, v: 18},
}, {
    "title": "Textured-knit Dress",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200231035%20001%2034%205946.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=5&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Dresses",
    "color": "White",
    "price": "$39.95",
    "description": "Fitted, knee-length dress in jersey with a textured pattern. Short sleeves, seam at waist, and wrap-front skirt. Lined.",
    "detail": "9% spandex, 91% polyester.",
    "history": 0,
    "hsv": {h: 41, s: 7, v: 93},
}, {
    "title": "Sleeveless Dress",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200216053%20004%2027%205905.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=4&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Dresses",
    "color": "White",
    "price": "$24.95",
    "description": "Short, sleeveless dress in airy woven fabric with embroidery. Elasticized seam at waist and gently flared skirt. Half-lined.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 252, s: 2, v: 94},
}, {
    "title": "Pleated Dress",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2QV%200215086%20001%2015%206151.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Office wear",
    "color": "Dark blue",
    "price": "$49.95",
    "description": "Sleeveless, pleated dress in airy, woven fabric. Elasticized seam at waist and button at back of neck. Lined.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 243, s: 32, v: 26},
}, {
    "title": "Strapless Dress",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2OV%200210888%20006%2097%205807.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Dresses",
    "color": "Blue/Patterned",
    "price": "$24.95",
    "description": "Long, strapless dress in airy chiffon. Elastication at top and below bust. High slit at one side. Lined with short liner dress.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 210, s: 67, v: 31},
}, {
    "title": "Chiffon Dress",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2OV%200213854%20001%2054%209849.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=0&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Dresses",
    "color": "Red",
    "price": "$29.95",
    "description": "Dress in airy, patterned chiffon with narrow, adjustable shoulder straps. Wrap-style front and longer back section. Short jersey liner skirt.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 350, s: 60, v: 72},
}, ];
var SKIRTS = [{
    "title": "Circular Skirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2QV%200209760%20021%2047%205894.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=5&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Skirts",
    "color": "Light pink",
    "price": "$14.95",
    "description": "Short circular skirt in jersey with elasticized waistband and zip at back. Unlined.",
    "detail": "67% polyester, 33% cotton.",
    "history": 0,
    "hsv": {h: 356, s: 13, v: 96},
}, {
    "title": "Lace Skirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200224720%20001%2051%206145.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Skirts",
    "color": "Natural white",
    "price": "$17.95",
    "description": "Short tiered lace skirt with concealed side zip. Lined.",
    "detail": "100% nylon.",
    "history": 0,
    "hsv": {h: 29, s: 13, v: 96},
}, {
    "title": "Knee-length Skirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200207051%20001%2046%208751.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Office wear",
    "color": "Dark blue",
    "price": "$29.95",
    "description": "Knee-length, flared skirt in woven stretch fabric with raw-edge hem. Concealed back zip. Lined.",
    "detail": "93% polyester, 7% spandex.",
    "history": 0,
    "hsv": {h: 250, s: 27, v: 26},
}, {
    "title": "Denim Skirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2OV%200221570%20002%2035%209226.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=5&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Skirts",
    "color": "Denim blue",
    "price": "$19.95",
    "description": "Short, 5-pocket skirt in washed denim with distressed details.",
    "detail": "99% cotton, 1% spandex.",
    "history": 0,
    "hsv": {h: 216, s: 24, v: 56},
}, {
    "title": "Maxi Skirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2QV%200216428%20001%2048%203638.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Skirts",
    "color": "Dark blue",
    "price": "$34.95",
    "description": "Maxi skirt in crinkled, woven fabric with decorative lace trim. Wide smocking at waist. Unlined.",
    "detail": "100% rayon.",
    "history": 0,
    "hsv": {h: 217, s: 37, v: 40},
}, ];
var PANTS = [{
    "title": "Harem Pants",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AB%200186372%20005%2016%201534.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=4&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Basics",
    "color": "Khaki green",
    "price": "$17.95",
    "description": "Harem pants in jersey with elastication at waist and hems.",
    "detail": "100% rayon.",
    "history": 0,
    "hsv": {h: 30, s: 18, v: 45},
}, {
    "title": "Slim-fit Twill Pants",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2HV%200190822%20038%2018%204539.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Pants",
    "color": "White",
    "price": "$19.95",
    "description": "5-pocket, slim-fit pants in washed superstretch twill with regular waist and slim legs.",
    "detail": "70% cotton, 3% spandex, 27% polyester.",
    "history": 0,
    "hsv": {h: 42, s: 7, v: 93},
}, {
    "title": "Slim-fit Twill Pants",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/V26%200190822%20004%2006%202253.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=0&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Pants",
    "color": "Black",
    "price": "$19.95",
    "description": "5-pocket, slim-fit pants in washed superstretch twill with regular waist and slim legs.",
    "detail": "3% spandex, 70% cotton, 27% polyester.",
    "history": 0,
    "hsv": {h: 290, s: 13, v: 18},
}, {
    "title": "Suit Pants",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2OV%200214395%20001%2066%203564.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Office wear",
    "color": "Black",
    "price": "$34.95",
    "description": "Pants in woven fabric with a slight sheen. Side pockets, pleats at waist, concealed side zip, and mock fly. Gently tapered legs.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 252, s: 16, v: 13},
}, {
    "title": "Linen-blend Pants",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2NV%200205449%20001%2036%209122.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Pants",
    "color": "Dark blue",
    "price": "$34.95",
    "description": "Pants in an airy linen and cotton blend with a washed look. Slightly wider legs, regular waist with drawstring, side pockets, and back welt pockets.",
    "detail": "45% cotton, 55% linen.",
    "history": 0,
    "hsv": {h: 222, s: 29, v: 27},
}, {
    "title": "Sweatpants",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2PV%200213974%20001%2016%209400.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Pants",
    "color": "Dark blue",
    "price": "$24.95",
    "description": "Melange sweatpants with 3/4-length legs. Elasticized drawstring waistband, printed motif on one leg, and ribbed hems.",
    "detail": "70% cotton, 30% polyester.",
    "history": 0,
    "hsv": {h: 243, s: 25, v: 29},
}, {
    "title": "Tuxedo Pants",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2MV%200211223%20009%2018%200380.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Pants",
    "color": "Natural white",
    "price": "$29.95",
    "description": "Tuxedo pants in lightweight, woven fabric with satin stripes at outer legs. Regular waist, hook-and-eye fastener, and pleats at top. Side pockets and one back welt pocket. Slightly wider, tapered legs.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 28, s: 6, v: 92},
}, {
    "title": "Slim-fit Chinos",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200222560%20002%2036%204863.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Pants",
    "color": "Beige",
    "price": "$29.95",
    "description": "Chinos in stretch cotton fabric with a regular waist and tapered legs. Side pockets, back welt pockets, and belt loops.",
    "detail": "98% cotton, 2% spandex.",
    "history": 0,
    "hsv": {h: 31, s: 19, v: 79},
}, {
    "title": "Slim-fit Chinos",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200222560%20003%2000%205138.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=0&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Pants",
    "color": "Red",
    "price": "$29.95",
    "description": "Chinos in stretch cotton fabric with a regular waist and tapered legs. Side pockets, back welt pockets, and belt loops.",
    "detail": "2% spandex, 98% cotton.",
    "history": 0,
    "hsv": {h: 351, s: 71, v: 95},
}, {
    "title": "Slacks",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2JV%200137860%20066%2095%204616.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Pants",
    "color": "Dark blue",
    "price": "$24.95",
    "description": "Regular-fit slacks in woven fabric with tapered, ankle-length legs, side pockets, and back welt pockets. Hook-and-eye fastener.",
    "detail": "2% spandex, 98% cotton.",
    "history": 0,
    "hsv": {h: 231, s: 29, v: 26},
}, ];
var JEANS = [{
    "title": "Super Skinny Super Low Jeans",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2IV%200158099%20001%2018%204538.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=5&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Jeans",
    "color": "Light denim blue",
    "price": "$29.95",
    "description": "&DENIM. 5-pocket ultra-low-rise jeans in washed stretch denim with ultra-slim legs.",
    "detail": "9% polyester, 90% cotton, 1% spandex.",
    "history": 0,
    "hsv": {h: 194, s: 6, v: 84},
}, {
    "title": "Boyfriend Skinny Jeans",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2GV%200200707%20002%2018%204557.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Jeans",
    "color": "Denim blue",
    "price": "$29.95",
    "description": "5-pocket jeans in washed stretch denim with heavily distressed patch details, regular waist, and tapered legs.",
    "detail": "2% spandex, 98% cotton.",
    "history": 0,
    "hsv": {h: 209, s: 31, v: 62},
}, {
    "title": "Skinny Low Ankle Jeans",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2BV%200194388%20001%2098%201996.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=0&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Jeans",
    "color": "Dark gray",
    "price": "$39.95",
    "description": "&DENIM. 5-pocket, low-rise biker jeans in washed stretch denim. Ultra-slim, ankle-length legs with zips at hems. Decorative pockets with concealed zip at front and pleats at back of waist. ONLINE EXCLUSIVE.",
    "detail": "2% spandex, 90% cotton, 8% polyester.",
    "history": 0,
    "hsv": {h: 333, s: 16, v: 23},
}, {
    "title": "Skinny High Jeans",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2HV%200209132%20001%2016%205887.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Jeans",
    "color": "Denim blue",
    "price": "$39.95",
    "description": "&DENIM. 5-pocket jeans in washed stretch denim with ultra-slim legs and a high waist.",
    "detail": "2% spandex, 98% cotton.",
    "history": 0,
    "hsv": {h: 216, s: 26, v: 40},
}, {
    "title": "Boot cut Low Jeans",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2NV%200192016%20001%2047%200071.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=5&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Jeans",
    "color": "White",
    "price": "$39.95",
    "description": "5-pocket, low-rise, bootcut jeans in stretch denim with distressed details.",
    "detail": "98% cotton, 2% spandex.",
    "history": 0,
    "hsv": {h: 255, s: 2, v: 94},
}, ];
var SHORTS = [{
    "title": "Short Twill Shorts",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2OV%200165378%20032%2036%209179.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shorts",
    "color": "Khaki green",
    "price": "$12.95",
    "description": "Short, 5-pocket slim-fit shorts in stretch cotton twill. Regular waist.",
    "detail": "2% spandex, 98% cotton.",
    "history": 0,
    "hsv": {h: 47, s: 18, v: 42},
}, {
    "title": "Chino Shorts",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200197582%20001%2028%204990.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shorts",
    "color": "Black",
    "price": "$17.95",
    "description": "Shorts in washed cotton twill with side pockets. One mock welt pocket at back, and sewn cuffs at hems.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 240, s: 18, v: 15},
}, {
    "title": "Chino Shorts",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2PV%200175404%20013%2035%209273.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shorts",
    "color": "Light pink",
    "price": "$24.95",
    "description": "Cotton chino shorts. Side pockets, back welt pockets with button, and sewn cuffs at hems.",
    "detail": "98% cotton, 2% spandex.",
    "history": 0,
    "hsv": {h: 11, s: 15, v: 91},
}, {
    "title": "Bermuda Shorts",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2MV%200231083%20001%2016%205885.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=4&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shorts",
    "color": "Black",
    "price": "$39.95",
    "description": "Knee-length shorts in woven fabric with pleats at front. Side pockets, back pockets with flap, and elastication at back of waist.",
    "detail": "39% polyester, 61% rayon.",
    "history": 0,
    "hsv": {h: 250, s: 17, v: 14},
}, {
    "title": "Denim Shorts",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2QV%200207930%20001%2096%209511.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shorts",
    "color": "Denim blue",
    "price": "$29.95",
    "description": "Short, 5-pocket shorts in washed stretch denim with distressed details. Sewn cuffs at hems.",
    "detail": "1% spandex, 99% cotton.",
    "history": 0,
    "hsv": {h: 219, s: 25, v: 48},
}, {
    "title": "Chino Shorts",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200175404%20010%2011%205456.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shorts",
    "color": "Blue/Striped",
    "price": "$24.95",
    "description": "Cotton chino shorts. Side pockets, back welt pockets with button, and sewn cuffs at hems.",
    "detail": "67% cotton, 33% polyester.",
    "history": 0,
    "hsv": {h: 227, s: 11, v: 82},
}, ];
var SPORTSWEAR = [{
    "title": "Sports Shorts",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200185093%20001%2047%209659.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Sportswear",
    "color": "Black",
    "price": "$12.95",
    "description": "Mesh-lined shorts in fast-drying, breathable functional fabric. Elasticized drawstring waistband with concealed key pocket.",
    "detail": "Quick-dry, 100% polyester.",
    "history": 0,
    "hsv": {h: 255, s: 9, v: 18},
}, {
    "title": "Running Tank Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200195477%20003%2035%205505.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Sportswear",
    "color": "Mint green",
    "price": "$19.95",
    "description": "Racerback tank top in fast-drying, functional fabric with ventilating dot pattern front and back. Rounded hem, slightly longer at back.",
    "detail": "Quick-dry, 27% spandex, 73% nylon.",
    "history": 0,
    "hsv": {h: 162, s: 34, v: 94},
}, {
    "title": "Tennis Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200198193%20002%2081%203490.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Sportswear",
    "color": "Coral",
    "price": "$24.95",
    "description": "Fitted tennis top in fast-drying, functional fabric. Short button placket and short puff sleeves.",
    "detail": "Quick-dry, 92% polyester, 8% spandex.",
    "history": 0,
    "hsv": {h: 9, s: 69, v: 98},
}, {
    "title": "Yoga Pants",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2QV%200202485%20001%2035%205502.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=4&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Sportswear",
    "color": "Light gray",
    "price": "$24.95",
    "description": "Melange yoga sweatpants. Elasticized waistband with concealed drawstring, one back pocket, and ribbed hems.",
    "detail": "77% cotton, 17% polyester, 6% rayon.",
    "history": 0,
    "hsv": {h: 30, s: 6, v: 81},
}, {
    "title": "Sports Pants",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2QV%200220153%20002%2035%205504.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Sportswear",
    "color": "Black",
    "price": "$24.95",
    "description": "3/4-length pants in fast-drying, functional fabric. Elasticized waistband and ribbed hems.",
    "detail": "Quick-dry, 12% spandex, 88% polyester.",
    "history": 0,
    "hsv": {h: 270, s: 10, v: 16},
}, {
    "title": "Sports Tank Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200195433%20002%2017%209622.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Sportswear",
    "color": "Dark gray",
    "price": "$14.95",
    "description": "Fitted tank top in fast-drying, functional fabric with ventilating mesh sections at back and sides. V-neck at front and back.",
    "detail": "Quick-dry, 17% spandex, 83% polyester.",
    "history": 0,
    "hsv": {h: 288, s: 10, v: 20},
}, {
    "title": "Canvas Sneakers",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/V25%200166213%20001%2070%204640%202.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Black",
    "price": "$12.95",
    "description": "Low canvas sneakers with laces and rubber soles.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 0, s: 0, v: 13},
}, {
    "title": "Sneakers",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AE%200193766%20001%2090%200300.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Black",
    "price": "$39.95",
    "description": "Racer-style sneakers with patterned sides, studs at back, and details in imitation leather and imitation suede. Mesh top sections and rubber soles. ONLINE EXCLUSIVE.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 300, s: 5, v: 15},
}, ];
var OFFICE_WEAR = [{
    "title": "Lace Dress",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200233002%20001%2035%205954.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Dresses",
    "color": "Natural white",
    "price": "$99",
    "description": "Long, sleeveless dress in an airy, woven fabric. Lace sections at top, and open back with button at back of neck. Seam at waist, elasticized at back, and skirt in lace and mesh. Lined.",
    "detail": "55% rayon, 45% cotton.",
    "history": 0,
    "hsv": {h: 37, s: 18, v: 94},
}, {
    "title": "Satin Dress",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2HV%200215227%20002%2036%202577.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Office wear",
    "color": "Dusty pink",
    "price": "$34.95",
    "description": "Fitted, knee-length dress in satin with draped wrapover front section. Short ruffled sleeves, seam at waist, and concealed back zip. Lined.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 9, s: 18, v: 84},
}, {
    "title": "Sleeveless Dress",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2OV%200210180%20003%2097%203173.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Dresses",
    "color": "Blue",
    "price": "$39.95",
    "description": "Knee-length dress in textured, woven stretch fabric. Fitted bodice and flared skirt. Concealed zip and slightly lower-cut neckline at back. Unlined.",
    "detail": "74% polyester, 25% rayon, 1% spandex.",
    "history": 0,
    "hsv": {h: 233, s: 55, v: 43},
}, {
    "title": "Sleeveless Dress",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2OV%200226211%20001%2048%203619.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Office wear",
    "color": "Black",
    "price": "$34.95",
    "description": "Knee-length, dress in woven fabric with a slight sheen. Fitted bodice, gently flared skirt, and concealed back zip. Lined.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 264, s: 13, v: 15},
}, {
    "title": "Flared Dress",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AV%200217426%20006%2035%207600.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Office wear",
    "color": "Gray",
    "price": "$34.95",
    "description": "Sleeveless, knee-length woven dress with fitted bodice and flared skirt. Seam at waist and removable imitation leather belt. Lined.",
    "detail": "63% polyester, 2% spandex, 35% rayon.",
    "history": 0,
    "hsv": {h: 0, s: 2, v: 51},
}, ];
var JACKETS_COATS = [{
    "title": "Denim Jacket",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200215281%20001%2095%202967.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Jackets & Coats",
    "color": "Denim blue",
    "price": "$39.95",
    "description": "&DENIM. Biker jacket in washed stretch denim with quilted details. Asymmetrical zip at front, small stand-up collar with lapels and snap fasteners, one front pocket with zip, and zips at cuffs.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 219, s: 39, v: 45},
}, {
    "title": "Denim Jacket",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2FV%200216887%20001%2046%203818.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Jackets & Coats",
    "color": "Black",
    "price": "$49.95",
    "description": "Jacket in hard-washed denim with imitation leather sleeves. Buttons at front, chest pockets with flap and button, and zips at cuffs.",
    "detail": "98% cotton, 2% spandex.",
    "history": 0,
    "hsv": {h: 300, s: 4, v: 18},
}, {
    "title": "Biker Jacket",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2EV%200206635%20003%2091%204525.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Jackets & Coats",
    "color": "Dark gray",
    "price": "$49.95",
    "description": "Biker jacket in imitation leather and suede. Diagonal zip and side pockets with zip at front, and zip at cuffs. Lined.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 312, s: 7, v: 27},
}, {
    "title": "Trenchcoat",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AV%200198418%20004%2021%207670.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Jackets & Coats",
    "color": "Beige",
    "price": "$69.95",
    "description": "Short trenchcoat with yoke, buttons at front, and shoulder tabs with concealed buttons. Side pockets, removable tie belt, and back vent. Satin lining.",
    "detail": "62% cotton, 36% rayon, 2% spandex.",
    "history": 0,
    "hsv": {h: 28, s: 16, v: 79},
}, {
    "title": "Quilted Jacket",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2BV%200204395%20001%2021%203938.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Jackets & Coats",
    "color": "Dark blue",
    "price": "$49.95",
    "description": "Fitted, quilted jacket with stand-up collar and front zip. Smartphone pocket at top with band attached to lining, band can be attached to smartphone for easy retrieval. Side pockets with snap fastener, adjustable tab with snap fasteners at cuffs, and rounded hem. Slightly longer at back.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 220, s: 25, v: 29},
}, ];
var PUMPS_HIGH_HEELS = [{
    "title": "Platform Pumps",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2JV%200162224%20003%2040%200381.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Blue",
    "price": "$10",
    "description": "Imitation suede peep-toe pumps. Front platform height 1 1/4 in., heel height 5 in.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 222, s: 62, v: 70},
}, {
    "title": "Sandalettes",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2OV%200211498%20001%2090%200641.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=6&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Beige",
    "price": "$39.95",
    "description": "High-heeled sandalettes in snakeskin-patterned and smooth imitation leather. Zip at heel. Heel height 4 1/4 in.",
    "detail": "100% polyurethane.",
    "history": 0,
    "hsv": {h: 25, s: 30, v: 76},
}, {
    "title": "Wedge-heel Sandalettes",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2OV%200211347%20002%2010%201062.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=3&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "White",
    "price": "$49.95",
    "description": "Sandals in cotton twill with a braided wedge heel. Decorative tulle roses at top and fastener at ankle. Heel height 4 1/4 in. Rubber soles.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 37, s: 11, v: 89},
}, {
    "title": "Pumps",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2012/P01%2006850%2007306%2010%200076%207.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&call=url[file:/product/large]",
    "gender": "Sale",
    "category": "LADIES",
    "color": "Gray",
    "price": "$10",
    "description": "Imitation suede pumps (neon pink in imitation patent leather). Heel height 3 in. Rubber soles.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 20, s: 5, v: 23},
}, {
    "title": "Leather Pumps",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200202826%20001%2080%202697.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Black",
    "price": "$49.95",
    "description": "PREMIUM QUALITY. Leather pumps with pointed toes. Heel height 4 in.",
    "detail": "100% leather.",
    "history": 0,
    "hsv": {h: 350, s: 10, v: 23},
}, ];
var SANDALS = [{
    "title": "Slip-on Sandals",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200207741%20002%2080%201144.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Black",
    "price": "$24.95",
    "description": "Slip-on sandals in imitation leather with rubber soles.",
    "detail": "100% polyurethane.",
    "history": 0,
    "hsv": {h: 24, s: 39, v: 73},
}, {
    "title": "Strappy Sandals",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200163730%20008%2060%201597.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=4&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Brown",
    "price": "$17.95",
    "description": "Strappy sandals in imitation leather with fastener at ankle.  Rubber soles.",
    "detail": "100% polyurethane.",
    "history": 0,
    "hsv": {h: 25, s: 39, v: 67},
}, {
    "title": "Flip-flops",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2JV%200205279%20002%2044%205175.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Swimwear",
    "color": "Black",
    "price": "$5.95",
    "description": "Flip-flops with imitation suede straps and straw insoles. Rubber soles.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 25, s: 26, v: 18},
}, {
    "title": "Flip-flops",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2OV%200224206%20001%2080%202716.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=0&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Black",
    "price": "$7.95",
    "description": "Flip-flops with rhinestone-trimmed rubber straps. Embossed rubber soles.",
    "detail": "100% rubber.",
    "history": 0,
    "hsv": {h: 330, s: 4, v: 20},
}, {
    "title": "Leather Sandals",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2OV%200201312%20002%2090%201732.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=6&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Rust red",
    "price": "$29.95",
    "description": "PREMIUM QUALITY. Sandals in leather with a metal buckle at side. Rubber soles.",
    "detail": "100% leather.",
    "history": 0,
    "hsv": {h: 14, s: 41, v: 49},
}, ];
var SHOES = [{
    "title": "Ballet Flats",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2KV%200207367%20011%2080%200173.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=0&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Powder pink",
    "price": "$12.95",
    "description": "Ballet flats with bow at front. Rubber soles.",
    "detail": "100% polyurethane.",
    "history": 0,
    "hsv": {h: 18, s: 27, v: 83},
}, {
    "title": "Platform Sneakers",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200156631%20008%2020%201423.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "White textured",
    "price": "$24.95",
    "description": "Platform sneakers in canvas with front laces and rubber soles. Platform height 1 1/4 in. ONLINE EXCLUSIVE.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 42, s: 9, v: 92},
}, {
    "title": "Sneakers",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2CA%200179368%20007%2050%201005.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=0&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Blue",
    "price": "$12.95",
    "description": "Sneakers with laces at front. Rubber soles.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 243, s: 25, v: 28},
}, {
    "title": "Sneakers",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2CV%200212042%20001%2000%204798.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=0&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Black",
    "price": "$14.95",
    "description": "Sneakers in canvas with laces and rubber soles.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 290, s: 16, v: 15},
}, {
    "title": "Sneakers",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2FV%200194970%20001%2070%208853.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "White",
    "price": "$49.95",
    "description": "Sneakers in imitation leather with printed snakeskin panels at sides. Studs and imitation suede band at back, laces at front, and decorative zips at sides. Rubber soles.",
    "detail": "100% polyurethane.",
    "history": 0,
    "hsv": {h: 43, s: 6, v: 92},
}, ];
var BOOTS = [{
    "title": "Biker Boots",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/1JV%200171200%20001%2090%205397.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Black",
    "price": "$20",
    "description": "Biker boots in imitation leather with decorative tabs and side zip (brown with imitation suede upper section and pile lining, and without zip). Rubber soles.",
    "detail": "100% polyurethane.",
    "history": 0,
    "hsv": {h: 280, s: 8, v: 14},
}, {
    "title": "Boots",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AV%200178914%20008%2020%209777.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=0&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Black/Canvas",
    "price": "$10",
    "description": "High boots. Front laces and chunky rubber soles.",
    "detail": "100% polyurethane.",
    "history": 0,
    "hsv": {h: 330, s: 14, v: 17},
}, {
    "title": "Leather Boots",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200203000%20002%2080%202653.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=1&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Brown",
    "price": "$79.95",
    "description": "PREMIUM QUALITY. Leather ankle boots with pointed toe and side zip. (Brown with adjustable strap at top with integral metal chain and metal buckle.) Rubber soles. Heel height 2 in.",
    "detail": "100% leather.",
    "history": 0,
    "hsv": {h: 27, s: 43, v: 66},
}, {
    "title": "Flat Boots",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/1JA%200183637%20002%2080%205819.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=6&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Brown",
    "price": "$34.95",
    "description": "Low boots in imitation suede with elastic side panels and satin lining. Rubber soles.",
    "detail": "100% polyurethane.",
    "history": 0,
    "hsv": {h: 27, s: 28, v: 38},
}, {
    "title": "Boots",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2BV%200170769%20003%2020%209778.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=2&call=url[file:/product/large]",
    "gender": "LADIES",
    "category": "Shoes",
    "color": "Beige",
    "price": "$29.95",
    "description": "Boots in imitation suede with laces and rubber soles.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 29, s: 29, v: 71},
}, ];
