var T_SHIRTS_VESTS = [{
    "title": "T-shirt with Printed Design",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200218033%20005%2081%200502.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "T-shirts & Vests",
    "color": "Turquoise",
    "price": "$12.95",
    "description": "T-shirt in cotton jersey with a printed design at front.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 192, s: 56, v: 82},
}, {
    "title": "T-shirt with Printed Design",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200218033%20006%2026%204162.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=4&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "T-shirts & Vests",
    "color": "Yellow",
    "price": "$12.95",
    "description": "T-shirt in cotton jersey with a printed design at front.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 49, s: 40, v: 85},
}, {
    "title": "T-shirt with Printed Design",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200218033%20004%2081%200501.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "T-shirts & Vests",
    "color": "Red",
    "price": "$12.95",
    "description": "T-shirt in cotton jersey with a printed design at front.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 359, s: 62, v: 82},
}, {
    "title": "V-neck T-shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2QV%200141562%20117%2096%200032.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "T-shirts & Vests",
    "color": "Green",
    "price": "$5.95",
    "description": "CONSCIOUS. V-neck T-shirt in organic cotton jersey.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 178, s: 63, v: 54},
}, {
    "title": "Printed T-shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200221114%20003%2041%200729.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=0&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "T-shirts & Vests",
    "color": "White",
    "price": "$12.95",
    "description": "Jersey T-shirt with a printed design at front.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 47, s: 4, v: 91},
}, {
    "title": "Polo Shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/1CA%200153906%20042%2037%202733.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "T-shirts & Vests",
    "color": "Dark blue",
    "price": "$9.95",
    "description": "Polo shirt in soft cotton with short button placket.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 216, s: 47, v: 27},
}, {
    "title": "T-shirt with Printed Design",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2KV%200202247%20019%2067%204722.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "T-shirts & Vests",
    "color": "Dark gray",
    "price": "$12.95",
    "description": "T-shirt in cotton jersey with printed design at front.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 345, s: 5, v: 33},
}, {
    "title": "T-shirt with Printed Design",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2CV%200202247%20016%2035%202196.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=4&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "T-shirts & Vests",
    "color": "Gray",
    "price": "$12.95",
    "description": "T-shirt in cotton jersey with printed design at front.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 40, s: 2, v: 68},
}, {
    "title": "T-shirt with Printed Design",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200218033%20008%2081%200503.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "T-shirts & Vests",
    "color": "Dark blue",
    "price": "$12.95",
    "description": "T-shirt in cotton jersey with a printed design at front.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 211, s: 57, v: 45},
}, {
    "title": "Cotton T-shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2OV%200228716%20001%2057%200545.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "T-shirts & Vests",
    "color": "Dark blue",
    "price": "$12.95",
    "description": "T-shirt in thick cotton jersey with a chest pocket.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 234, s: 24, v: 31},
}, {
    "title": "Hooded T-shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2MV%200202578%20001%2068%200472.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "T-shirts & Vests",
    "color": "Dark gray",
    "price": "$17.95",
    "description": "Hooded jersey T-shirt with high collar and a rolled raw-edge hem.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 252, s: 5, v: 40},
}, {
    "title": "T-shirt with Printed Design",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200217701%20006%2051%206144.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "T-shirts & Vests",
    "color": "White",
    "price": "$12.95",
    "description": "T-shirt in cotton jersey with a printed design at front.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 240, s: 0, v: 95},
}, ];
var SHIRTS = [{
    "title": "Short-sleeved Poplin Shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200209263%20003%2041%200726.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shirts",
    "color": "Turquoise",
    "price": "$17.95",
    "description": "Short-sleeved shirt in checked cotton poplin with button-down collar and one chest pocket. Regular fit.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 177, s: 32, v: 85},
}, {
    "title": "Short-sleeved Poplin Shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200209263%20001%2015%204093.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shirts",
    "color": "Red",
    "price": "$17.95",
    "description": "Short-sleeved shirt in checked cotton poplin with button-down collar and one chest pocket. Regular fit.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 354, s: 11, v: 76},
}, {
    "title": "Short-sleeved Poplin Shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200209263%20004%2041%200728.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shirts",
    "color": "Dark blue",
    "price": "$17.95",
    "description": "Short-sleeved shirt in checked cotton poplin with button-down collar and one chest pocket. Regular fit.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 210, s: 10, v: 72},
}, ];
var HOODIES_SWEATSHIRTS = [{
    "title": "Hooded Jacket",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AV%200118441%20073%2021%203936.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=0&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Hoodies & Sweatshirts",
    "color": "Green",
    "price": "$19.95",
    "description": "Hooded jacket in sweatshirt fabric. Jersey-lined hood with a thick drawstring, zip and pockets at front, and ribbed cuffs and hem. Soft, brushed inside.",
    "detail": "40% polyester, 60% cotton.",
    "history": 0,
    "hsv": {h: 149, s: 26, v: 35},
}, {
    "title": "Printed Hooded Sweatshirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2CV%200205026%20004%2035%204261.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Hoodies & Sweatshirts",
    "color": "Red",
    "price": "$24.95",
    "description": "Long-sleeved sweatshirt with printed design at front, jersey-lined drawstring hood, and kangaroo pocket. Ribbed cuffs and hem.",
    "detail": "20% polyester, 80% cotton.",
    "history": 0,
    "hsv": {h: 357, s: 57, v: 63},
}, {
    "title": "Hooded Jacket",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200216557%20002%2064%202770.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Hoodies & Sweatshirts",
    "color": "Dark blue",
    "price": "$34.95",
    "description": "Jacket in melange sweatshirt fabric. Jersey-lined drawstring hood, zip at front, side pockets, and ribbed cuffs and hem. Soft, brushed inside.",
    "detail": "47% polyester, 53% cotton.",
    "history": 0,
    "hsv": {h: 219, s: 35, v: 31},
}, {
    "title": "Hooded Jacket",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200216557%20003%2064%202769.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Hoodies & Sweatshirts",
    "color": "Gray/striped",
    "price": "$34.95",
    "description": "Jacket in melange sweatshirt fabric. Jersey-lined drawstring hood, zip at front, side pockets, and ribbed cuffs and hem. Soft, brushed inside.",
    "detail": "53% cotton, 47% polyester.",
    "history": 0,
    "hsv": {h: 40, s: 2, v: 72},
}, {
    "title": "Sweatshirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/1CV%200103125%20031%2031%203054.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=5&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Hoodies & Sweatshirts",
    "color": "Black",
    "price": "$12.95",
    "description": "Sweatshirt in soft fabric. Brushed inside.",
    "detail": "48% cotton, 52% polyester.",
    "history": 0,
    "hsv": {h: 290, s: 14, v: 17},
}, ];
var SWEATERS_CARDIGANS = [{
    "title": "Pattern-knit Sweater",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2MV%200211139%20003%2031%206323.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Sweaters & Cardigans",
    "color": "Beige",
    "price": "$39.95",
    "description": "Long-sleeved, pattern-knit sweater in cotton.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 30, s: 28, v: 45},
}, {
    "title": "Textured-knit Sweater",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2NV%200193579%20002%2068%205038.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=0&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Sweaters & Cardigans",
    "color": "Dark teal",
    "price": "$59.95",
    "description": "Long-sleeved, fine-knit, bubble-texture sweater with ribbed cuffs and hem.",
    "detail": "68% cotton, 28% polyester, 4% spandex.",
    "history": 0,
    "hsv": {h: 194, s: 25, v: 27},
}, {
    "title": "Texture-knit Sweater",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2MV%200193980%20003%2018%200377.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Sweaters & Cardigans",
    "color": "Beige",
    "price": "$34.95",
    "description": "Texture-knit sweater in cotton with a rolled-edge neckline.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 33, s: 8, v: 85},
}, {
    "title": "Knit Sweater",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2BV%200205744%20001%2015%203705.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Sweaters & Cardigans",
    "color": "Black/58",
    "price": "$29.95",
    "description": "Long-sleeved knit sweater in a wool blend with intarsia pattern. Round neckline.",
    "detail": "85% wool, 15% acrylic.",
    "history": 0,
    "hsv": {h: 48, s: 2, v: 83},
}, {
    "title": "Cardigan",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2BV%200194995%20001%2056%207795.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Sweaters & Cardigans",
    "color": "Gray",
    "price": "$10",
    "description": "Fine-knit cotton cardigan with buttons at front.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 300, s: 2, v: 50},
}, ];
var JACKETS_COATS = [{
    "title": "Padded Parka",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/1JV%200176519%20001%2076%203406.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=4&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jackets & Coats",
    "color": "Black",
    "price": "$69.95",
    "description": "Padded parka in woven fabric with quilted lining. Lined hood with detachable faux fur trim. Zip and buttons at front. Side pockets with snap fasteners, pockets at front with flap and button, and one inner pocket. Concealed drawstring at waist and adjustable Velcro tabs at cuffs.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 290, s: 13, v: 19},
}, {
    "title": "Linen Jacket",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2KV%200201297%20001%2086%209963.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jackets & Coats",
    "color": "Black",
    "price": "$69.95",
    "description": "Jacket in woven linen fabric with asymmetrical front zip. Lined.",
    "detail": "100% linen.",
    "history": 0,
    "hsv": {h: 280, s: 6, v: 19},
}, {
    "title": "Canvas Parka",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2JV%200199977%20003%2086%209989.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jackets & Coats",
    "color": "Khaki green",
    "price": "$49.95",
    "description": "Parka in washed cotton canvas with chambray-lined drawstring hood. Concealed zip and snap fasteners at front, side pockets with flap and snap fastener, and adjustable cuffs with snap fasteners. Drawstring at hem. Unlined.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 41, s: 14, v: 45},
}, {
    "title": "Denim Jacket",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2GV%200202005%20001%2018%203752.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jackets & Coats",
    "color": "Denim blue",
    "price": "$39.95",
    "description": "&DENIM. Jacket in washed denim. Chest pockets with flap and fastener. Side pockets, tabs at sides, and cuffs with fasteners.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 212, s: 27, v: 51},
}, {
    "title": "Pilot Jacket",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2QV%200215639%20001%2016%209652.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jackets & Coats",
    "color": "Dark gray",
    "price": "$59.95",
    "description": "Lightweight pilot jacket with small, stand-up collar and front zip. Side pockets with snap fastener, pocket on one sleeve with zip, and ribbed cuffs and hem. Lined.",
    "detail": "100% lyocell.",
    "history": 0,
    "hsv": {h: 207, s: 18, v: 19},
}, ];
var JACKETS_SUITS = [{
    "title": "Linen Suit Jacket",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200212496%20003%2017%209711.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jackets & Suits",
    "color": "Dark gray",
    "price": "$99",
    "description": "PREMIUM QUALITY. Jacket in melange linen fabric. Chest pocket with attached handkerchief, front welt pockets with flap, and four inner pockets. Decorative buttons at cuffs and vent at back. Lined. Slim fit.",
    "detail": "100% linen.",
    "history": 0,
    "hsv": {h: 270, s: 7, v: 24},
}, {
    "title": "Linen Suit Pants",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200224363%20001%2034%205945.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jackets & Suits",
    "color": "Dark gray",
    "price": "$59.95",
    "description": "PREMIUM QUALITY. Linen suit pants with a hook-and-eye fastener, side pockets, and back welt pockets with button. Slim fit.",
    "detail": "100% linen.",
    "history": 0,
    "hsv": {h: 252, s: 8, v: 23},
}, {
    "title": "Melange Blazer",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2PV%200209414%20001%2035%205486.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=4&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jackets & Suits",
    "color": "Gray",
    "price": "$69.95",
    "description": "Blazer in melange woven fabric. Chest pocket, welt pockets at front, and three inner pockets. Decorative buttons at cuffs and vent at back. Satin lining. Slim fit.",
    "detail": "12% rayon, 88% polyester.",
    "history": 0,
    "hsv": {h: 218, s: 5, v: 65},
}, {
    "title": "Suit Pants",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2PV%200209407%20001%2011%205905.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jackets & Suits",
    "color": "Gray",
    "price": "$34.95",
    "description": "Suit pants in melange woven fabric. Side pockets, back welt pockets with button, and hook-and-eye fastener. Slim fit.",
    "detail": "12% rayon, 88% polyester.",
    "history": 0,
    "hsv": {h: 222, s: 6, v: 65},
}, {
    "title": "Linen-blend Blazer",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2NV%200198237%20001%2067%202292.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jackets & Suits",
    "color": "Dark blue",
    "price": "$99",
    "description": "Slim-fit blazer in a cotton and linen blend. Chest pocket with decorative handkerchief, front pockets with flap, and four inner pockets, one with button. Decorative buttonhole on lapel, decorative buttons at cuffs, and vent at back. Lined.",
    "detail": "52% linen, 48% cotton.",
    "history": 0,
    "hsv": {h: 237, s: 33, v: 24},
}, {
    "title": "Linen-blend Suit Pants",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2NV%200205181%20001%2081%203501.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jackets & Suits",
    "color": "Dark blue",
    "price": "$49.95",
    "description": "Suit pants in a cotton and linen blend. Hook-and-eye fastener, side pockets, back welt pockets with button, and coin pocket.",
    "detail": "48% cotton, 52% linen.",
    "history": 0,
    "hsv": {h: 230, s: 35, v: 27},
}, ];
var PANTS = [{
    "title": "Chinos Slim fit",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200200144%20003%2036%204859.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Pants",
    "color": "Dark blue",
    "price": "$24.95",
    "description": "Chinos in soft, washed cotton fabric with side pockets, coin pocket at front, and back welt pockets. Slim fit.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 234, s: 17, v: 24},
}, {
    "title": "Linen Pants Slim fit",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200208733%20001%2091%205622.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jackets & Suits",
    "color": "Beige",
    "price": "$34.95",
    "description": "Linen suit pants with hook-and-eye fastener, side pockets, and buttoned back welt pockets. Slim fit.",
    "detail": "100% linen.",
    "history": 0,
    "hsv": {h: 32, s: 7, v: 83},
}, {
    "title": "Chinos Slim fit",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RA%200200144%20013%2026%204155.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Pants",
    "color": "Dark beige",
    "price": "$24.95",
    "description": "Chinos in soft, washed cotton fabric with side pockets, coin pocket at front, and back welt pockets. Slim fit.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 34, s: 43, v: 62},
}, {
    "title": "Twill Pants Slim fit",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2EV%200219002%20003%2097%204748.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Pants",
    "color": "Dark blue",
    "price": "$24.95",
    "description": "5-pocket pants in washed stretch twill with slim legs, regular waist, and button fly.",
    "detail": "2% spandex, 98% cotton.",
    "history": 0,
    "hsv": {h: 230, s: 38, v: 42},
}, {
    "title": "Twill Pants Slim fit",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2EV%200219002%20011%2097%204747.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Pants",
    "color": "Light gray",
    "price": "$24.95",
    "description": "5-pocket pants in washed stretch twill with slim legs, regular waist, and button fly.",
    "detail": "98% cotton, 2% spandex.",
    "history": 0,
    "hsv": {h: 230, s: 3, v: 87},
}, ];
var JEANS = [{
    "title": "Jeans Slim Fit",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AV%200194069%20006%2056%203724.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jeans",
    "color": "Black",
    "price": "$34.95",
    "description": "5-pocket jeans in washed stretch denim. Regular waist, slim legs, and button fly.",
    "detail": "98% cotton, 2% spandex.",
    "history": 0,
    "hsv": {h: 288, s: 11, v: 18},
}, {
    "title": "Jeans Slim Fit",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AV%200194069%20007%2056%203730.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jeans",
    "color": "Light beige",
    "price": "$34.95",
    "description": "5-pocket jeans in washed stretch denim. Regular waist, slim legs, and button fly.",
    "detail": "98% cotton, 2% spandex.",
    "history": 0,
    "hsv": {h: 38, s: 9, v: 85},
}, {
    "title": "Jeans Slim Fit",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2JV%200194069%20001%2038%204822.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jeans",
    "color": "Blue",
    "price": "$34.95",
    "description": "5-pocket jeans in washed stretch denim. Regular waist, slim legs, and button fly.",
    "detail": "2% spandex, 98% cotton.",
    "history": 0,
    "hsv": {h: 210, s: 29, v: 59},
}, {
    "title": "Jeans Regular fit",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200199022%20001%2011%205225.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jeans",
    "color": "Light denim blue",
    "price": "$49.95",
    "description": "5-pocket jeans in washed denim with distressed details. Regular waist, slightly tapered legs, and button fly.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 213, s: 12, v: 71},
}, {
    "title": "Straight Regular Jeans",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/1AA%200143891%20001%2085%202631.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=8&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Jeans",
    "color": "Denim blue",
    "price": "$39.95",
    "description": "&DENIM/CONSCIOUS. 5-pocket jeans in washed, organic cotton denim. Regular waist, straight legs, and button fly.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 221, s: 21, v: 31},
}, ];
var SHORTS = [{
    "title": "Chino Shorts",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/V25%200122995%20033%2037%201341.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=5&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shorts",
    "color": "Black",
    "price": "$12.95",
    "description": "Shorts in washed cotton fabric. Side pockets, one back welt with button, and button fly.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 290, s: 16, v: 15},
}, {
    "title": "Sweatpant Shorts",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200220252%20001%2081%200519.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shorts",
    "color": "Grey",
    "price": "$24.95",
    "description": "Sweatpant shorts with elasticized drawstring waistband. Side pockets and back pocket with zip.",
    "detail": "30% polyester, 70% cotton.",
    "history": 0,
    "hsv": {h: 252, s: 3, v: 73},
}, {
    "title": "Chino Shorts",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200194058%20023%2018%205328.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=3&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shorts",
    "color": "Light beige",
    "price": "$24.95",
    "description": "5-pocket shorts in washed cotton twill.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 34, s: 14, v: 86},
}, {
    "title": "Chino Shorts",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2RV%200194058%20029%2096%209443.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shorts",
    "color": "Khaki green",
    "price": "$24.95",
    "description": "5-pocket shorts in washed cotton twill.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 47, s: 19, v: 49},
}, {
    "title": "Denim Shorts",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200199761%20001%2015%204943.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shorts",
    "color": "Denim blue",
    "price": "$29.95",
    "description": "5-pocket shorts in washed denim with sewn cuffs at hems and button fly.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 206, s: 23, v: 57},
}, ];
var SPORTSWEAR = [{
    "title": "Running Top",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200214414%20003%2036%208673.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Sportswear",
    "color": "Neon orange",
    "price": "$17.95",
    "description": "Short-sleeved running top in fast-drying, breathable functional fabric. Inset ventilating detail on one sleeve and reflective print at back. Regular fit.",
    "detail": "Quick-dry, Reflective details, 100% polyester.",
    "history": 0,
    "hsv": {h: 16, s: 77, v: 98},
}, {
    "title": "Running Shorts",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AV%200150519%20001%2094%201312.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Sportswear",
    "color": "Black",
    "price": "$24.95",
    "description": "Shorts in fast-drying, breathable functional fabric with gusset in cool, ventilating mesh. Elasticized waistband with drawstring and concealed key pocket. Side pockets. Lined. Regular fit.",
    "detail": "Quick-dry, Reflective details, 100% polyester.",
    "history": 0,
    "hsv": {h: 290, s: 14, v: 17},
}, {
    "title": "Running T-shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200210417%20001%2036%208666.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Sportswear",
    "color": "Light gray",
    "price": "$17.95",
    "description": "Short-sleeved running T-shirt in fast-drying, breathable functional fabric. Back pocket with zip, taped trim detail at back with ventilating holes, and rounded hem. Slightly longer at back. Regular fit. Size of pocket 3 1/2 x 5 in.",
    "detail": "Quick-dry, 58% cotton, 42% polyester.",
    "history": 0,
    "hsv": {h: 230, s: 3, v: 84},
}, {
    "title": "Running Shorts",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2PV%200191773%20006%2018%203355.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=0&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Sportswear",
    "color": "Dark orange",
    "price": "$29.95",
    "description": "Running shorts in fast-drying, breathable functional fabric. Elasticized waistband with concealed drawstring, zipped key pocket with reflective detail on one side, mesh at gusset, and ventilating leg panels. Mesh liner shorts. Regular fit.",
    "detail": "Quick-dry, Reflective details, 100% polyester.",
    "history": 0,
    "hsv": {h: 11, s: 78, v: 92},
}, {
    "title": "Sleeveless Sports Shirt",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/V18%200175097%20001%2023%202397.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=5&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Sportswear",
    "color": "White",
    "price": "$12.95",
    "description": "CONSCIOUS. Ergonomic sleeveless sports shirt in fast-drying, breathable functional fabric. Back section in cool mesh. Made from recycled material. Slim fit.",
    "detail": "Quick-dry, Reflective details, 94% polyester, 6% spandex.",
    "history": 0,
    "hsv": {h: 0, s: 0, v: 93},
}, {
    "title": "Athletic Pants",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AV%200156610%20001%2094%201292.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_FRONT]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Sportswear",
    "color": "Black",
    "price": "$24.95",
    "description": "CONSCIOUS. Athletic pants in fast-drying, breathable functional fabric made from recycled material. Side pockets, elasticized drawstring waistband, and zips at leg hems. Small coin pocket inside waistband.",
    "detail": "Quick-dry, 100% polyester.",
    "history": 0,
    "hsv": {h: 300, s: 28, v: 13},
}, ];
var SHOES = [{
    "title": "Suede Sneakers",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2BV%200189695%20002%2060%208862.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Dark brown",
    "price": "$59.95",
    "description": "PREMIUM QUALITY. Suede sneakers with front laces and rubber soles.",
    "detail": "100% suede.",
    "history": 0,
    "hsv": {h: 0, s: 30, v: 25},
}, {
    "title": "Suede Derby Shoes",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2KV%200173109%20007%2080%200179.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Nougat",
    "price": "$69.95",
    "description": "PREMIUM QUALITY. Derby shoes in suede with open laces and rubber soles.",
    "detail": "100% suede.",
    "history": 0,
    "hsv": {h: 28, s: 37, v: 69},
}, {
    "title": "Sneakers",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2AE%200189667%20003%2060%208896.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Dark blue",
    "price": "$19.95",
    "description": "Canvas sneakers with laces and rubber soles.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 222, s: 16, v: 25},
}, {
    "title": "Shoes",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2BV%200173533%20006%2060%208898.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Dark blue",
    "price": "$29.95",
    "description": "Canvas shoes with laces and rubber soles.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 217, s: 35, v: 38},
}, {
    "title": "Sneakers",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2CA%200193355%20001%2030%201274.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=0&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Black",
    "price": "$39.95",
    "description": "Sneakers in imitation suede with imitation leather details. Laces and rubber soles.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 280, s: 7, v: 17},
}, ];
var SANDALS_ESPADRILLES = [{
    "title": "Leather Flip-flops",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2SV%200166561%20005%2090%201428.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=0&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Brown",
    "price": "$29.95",
    "description": "PREMIUM QUALITY. Leather flip-flops with rubber soles.",
    "detail": "100% leather.",
    "history": 0,
    "hsv": {h: 26, s: 53, v: 82},
}, {
    "title": "Espadrilles with Laces",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2JV%200204721%20009%2080%201448.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=0&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Beige",
    "price": "$17.95",
    "description": "Espadrilles with laces at front and rubber soles.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 35, s: 36, v: 58},
}, {
    "title": "Shoes",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2PV%200206533%20008%2080%201477.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=3&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Dark blue",
    "price": "$24.95",
    "description": "Shoes in canvas and mesh with elastic panels at sides, imitation leather details, and rubber soles.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 211, s: 48, v: 25},
}, {
    "title": "Flip-flops",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200176459%20004%2090%200332.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Black",
    "price": "$12.95",
    "description": "Flip-flops with straps in imitation leather and denim. Straw insoles and rubber soles.",
    "detail": "60% cotton, 40% polyurethane.",
    "history": 0,
    "hsv": {h: 42, s: 32, v: 76},
}, {
    "title": "Espadrilles",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2014/2LV%200204724%20003%2080%200181.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Black",
    "price": "$12.95",
    "description": "Cotton canvas espadrilles with rubber soles.",
    "detail": "100% cotton.",
    "history": 0,
    "hsv": {h: 250, s: 14, v: 16},
}, ];
var BOOTS = [{
    "title": "Leather Chelsea Boots",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2BV%200181818%20001%2060%208911.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Black",
    "price": "$99",
    "description": "PREMIUM QUALITY. Classic Chelsea boots with elastic panels at sides and rubber soles. (Black in leather, dark brown in suede.)",
    "detail": "100% leather.",
    "history": 0,
    "hsv": {h: 290, s: 13, v: 18},
}, {
    "title": "Leather Boots",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2CA%200197435%20001%2080%200055.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=3&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Black",
    "price": "$129",
    "description": "PREMIUM QUALITY. Leather boots with laces, canvas lining, and rubber soles.",
    "detail": "100% leather.",
    "history": 0,
    "hsv": {h: 0, s: 7, v: 18},
}, {
    "title": "Leather Desert Boots",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2BV%200180608%20001%2060%208900.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Taupe",
    "price": "$79.95",
    "description": "PREMIUM QUALITY. Desert boots in nubuck leather with open laces and rubber soles.",
    "detail": "100% leather.",
    "history": 0,
    "hsv": {h: 29, s: 21, v: 69},
}, {
    "title": "Desert Boots",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/1CA%200171275%20005%2030%201272%201.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=1&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Khaki green",
    "price": "$49.95",
    "description": "Desert boots in imitation suede with canvas lining and rubber soles.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 42, s: 27, v: 34},
}, {
    "title": "Desert Boots",
    "image": "http://lp.hm.com/hmprod?set=key[source],value[/model/2013/2BV%200212591%20002%2060%208866.jpg]&set=key[rotate],value[]&set=key[width],value[]&set=key[height],value[]&set=key[x],value[]&set=key[y],value[]&set=key[type],value[STILL_LIFE_BACK]&hmver=2&call=url[file:/product/large]",
    "gender": "MEN",
    "category": "Shoes",
    "color": "Dark blue",
    "price": "$49.95",
    "description": "Desert boots in imitation suede with open laces and rubber soles.",
    "detail": "100% polyester.",
    "history": 0,
    "hsv": {h: 240, s: 13, v: 22},
}, ];
